# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ZaG/Desktop/vivado_project/final/final/final.srcs/sources_1/ip/Vga_25MH/Vga_25MH.xci
# IP: The module: 'Vga_25MH' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ZaG/Desktop/vivado_project/final/final/final.srcs/sources_1/ip/Vga_25MH/Vga_25MH.xci
# IP: The module: 'Vga_25MH' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/Vga_25MH/Vga_25MH_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Vga_25MH'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
