# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ZaG/Desktop/vivado_project/final/final/final.srcs/sources_1/ip/BRAM_image_g/BRAM_image_g.xci
# IP: The module: 'BRAM_image_g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/BRAM_image_g/BRAM_image_g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_image_g'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/ZaG/Desktop/vivado_project/final/final/final.srcs/sources_1/ip/BRAM_image_g/BRAM_image_g.xci
# IP: The module: 'BRAM_image_g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZaG/Desktop/vivado_project/final/final/final.gen/sources_1/ip/BRAM_image_g/BRAM_image_g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_image_g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
